---
- name: "Services install"
  hosts: all
  become: yes
  vars:
    - apache_timeout: 150
    - httpd_Server_admin: mathias@localhost
  tasks:
    - name: "Update all packages"
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: "Install dovecot on Debian"
      ansible.builtin.package:
        name:
          - dovecot-core
          - dovecot-imapd 
          - dovecot-pop3d
        state: present
      when: ansible_os_family == "Debian"
    
    - name: "Install dovecot on Rocky"
      ansible.builtin.package:
        name: dovecot          
        state: present
      when: ansible_os_family == "Rocky"
  
    - name: "Install httpd"
      ansible.builtin.package:
        name: httpd
        state: present
      when: ansible_os_family == "Rocky"
    
    - name: "Install apache"
      ansible.builtin.package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    
 #   - name: "Install squirrelmail"
 #     ansible.builtin.package:
 #       name: squirrelmail
 #       state: present
 #     when: ansible_os_family == "Debian"
   
    - name: Update dovecot configuration.
      ansible.builtin.template:
        src: ./template/dovecotconf.j2
        dest: /etc/dovecot/dovecot.conf
        #owner: mathias
        #group: mathias
        #mode: '0644'
  
    - name: Update apache2 configuration.
      ansible.builtin.template:
        src: ./template/apacheconf.j2
        dest: /etc/apache2/apache2.conf
      when: ansible_os_family == "Debian"
 
    - name: Update httpd configuration.
      ansible.builtin.template:
        src: ./template/httpdconf.j2
        dest: /etc/httpd/conf/httpd.conf
      when: ansible_os_family == "Rocky"