---
- name: "Tomcat Installation"
  hosts: all
  become: yes
  tasks:
#    - name: "Update cache"
#      ansible.builtin.package:
#        name: "*"
#        state: present
#    - name: "Update Rocky cache"
#      ansible.builtin.dnf:
#        name: "*"
#        state: present
#      when: ansible_os_family == "Rocky"
#    - name: "install java on debian"
#      ansible.builtin.package:
#        name: default-jdk
#        state: present
    - name: "install java on rocky"
      ansible.builtin.package:
        name: java-11-openjdk-devel #convertir a variable
        state: present
      when: ansible_os_family == "Rocky"
   
    - name: "install java"
      ansible.builtin.package:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"
    
    - name: "Add tomcat group"
      ansible.builtin.group:
        name: tomcat
        state: present
 
    - name: "Add tomcat user without shell"
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        groups: tomcat
        home: /opt/tomcat
        append: yes 

#    - name: Unarchive a file that is already on the remote machine
#    ansible.builtin.unarchive:
#      src: /tmp/foo.zip
#      dest: /usr/local/bin
#      remote_src: yes

    - name: "Decompress tomcat"
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz #convertir a variable
        dest: /opt/tomcat
        remote_src: yes
        extra_opts:
          - --strip-components=1
#    - name: Unarchive a file with extra options
#      ansible.builtin.unarchive:
#        src: /tmp/foo.zip
#        dest: /usr/local/bin
#        extra_opts:
#          - --transform
          
  
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
       path: /opt/tomcat
       state: directory
       recurse: yes
       owner: tomcat
       group: tomcat

    - name: "Add tomcat service on rocky"
      ansible.builtin.template:
        src: ./template/tomcatsvs2.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_os_family == "Rocky"
    
    - name: "Add tomcat service on debian"
      ansible.builtin.template:
          src: ./template/tomcatsvs.j2
          dest: /etc/systemd/system/tomcat.service
    
    - name: "daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true
        name: tomcat
        state: started

    - name: "add tomcat port on rocky"
      firewalld:
        port: 8080/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_os_family == "Rocky"