---
- name: "Services install"
  hosts: all
  become: yes
  tasks:
    - name: "Update all packages"
      ansible.builtin.package:
        name: "*"
        state: latest
 
    - name: "remove postfix"
      ansible.builtin.package:
        name: postfix
        state: absent

    - name: "Remove dovecot on Debian"
      ansible.builtin.package:
        name:
          - dovecot-core
          - dovecot-imapd 
          - dovecot-pop3d
        state: absent
      when: ansible_os_family == "Debian"
    
    - name: "remove dovecot on Rocky"
      ansible.builtin.package:
        name: dovecot          
        state: absent
      when: ansible_os_family == "Rocky"
  
    - name: "remove httpd"
      ansible.builtin.package:
        name: httpd
        state: absent
      when: ansible_os_family == "Rocky"
    
    - name: "remove apache"
      ansible.builtin.package:
        name: apache2
        state: absent
      when: ansible_os_family == "Debian"
    
    - name: "remove squirrelmail"
      ansible.builtin.package:
        name: squirrelmail
        state: absent
      when: ansible_os_family == "Debian"
