---
- name: "Update all packages"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages for Rocky
      ansible.builtin.dnf:
        name: "*"
        state: latest
    when: ansible_os_family == "Rocky" 
  
  - name: Update all packages for Debian
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_os_family == "Debian"
...