---
    - name: "install java on rocky"
      ansible.builtin.package:
        name: java-11-openjdk-devel #convertir a variable
        state: present
      when: ansible_os_family == "Rocky"
   
    - name: "install java on debian"
      ansible.builtin.package:
        name: default-jdk # convertir a variable
        state: present
      when: ansible_os_family == "Debian"
    
    - name: "Add tomcat group"
      ansible.builtin.group:
        name: tomcat
        state: present
 
    - name: "Add tomcat user without shell"
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        groups: tomcat
        home: /opt/tomcat
        append: yes 


    - name: "Decompress tomcat"
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz #convertir a variable
        dest: /opt/tomcat
        remote_src: yes
        extra_opts:
          - --strip-components=1
       
  
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
       path: /opt/tomcat
       state: directory
       recurse: yes
       owner: tomcat
       group: tomcat

    - name: "Add tomcat service on rocky"
      ansible.builtin.template:
        src: ./template/tomcatsvs2.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_os_family == "Rocky"
    
    - name: "Add tomcat service on debian"
      ansible.builtin.template:
          src: ./template/tomcatsvs.j2
          dest: /etc/systemd/system/tomcat.service
      when: ansible_os_family == "Debian"
    
    - name: "daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true
        name: tomcat
        state: started
        enabled: yes

    - name: "add tomcat port on rocky"
      firewalld:
        port: 8080/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_os_family == "Rocky"

    - name: "Create config directory"
      ansible.builtin.file:
        path: /opt/config
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: "copy .war file"
      ansible.builtin.copy:
        src: resources/todo.war
        dest: /opt/tomcat/webapps/todo.war
        owner: tomcat
        group: tomcat
        mode: '0644'
    
    - name: "copy app.properties"
      ansible.builtin.copy:
        src: resources/app.properties
        dest: /opt/config/app.properties 
# tasks file for tomcat
