---
    - name: "install java on rocky"
      ansible.builtin.package:
        name: java-11-openjdk-devel #convertir a variable
        state: present
      when: ansible_os_family == "RedHat"
   
    - name: "install java on debian"
      ansible.builtin.package:
        name: default-jdk # convertir a variable
        state: present
      when: ansible_os_family == "Debian"
    
    - name: "Add tomcat group"
      ansible.builtin.group:
        name: tomcat
        state: present
 
    - name: "Add tomcat user without shell"
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        groups: tomcat
        home: "{{  tomcat_folder_location  }}"
        append: yes 


    - name: "Decompress tomcat"
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v{{  tomcat_version  }}/bin/apache-tomcat-{{  tomcat_version  }}.tar.gz #convertir a variable
        dest: "{{  tomcat_folder_location  }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1
       
  
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
       path: "{{  tomcat_folder_location  }}"
       state: directory
       recurse: yes
       owner: tomcat
       group: tomcat

    - name: "Add tomcat service on rocky"
      ansible.builtin.template:
        src: ./template/tomcatsvs2.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_os_family == "RedHat"
    
    - name: "Add tomcat service on debian"
      ansible.builtin.template:
          src: ./template/tomcatsvs.j2
          dest: /etc/systemd/system/tomcat.service
      when: ansible_os_family == "Debian"
    
    - name: "daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true
        name: tomcat
        state: started
        enabled: yes

    - name: "add tomcat port on rocky"
      firewalld:
        port: "{{ rocky_firewall_tomcat_port }}"
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_os_family == "RedHat"

    - name: "Create config directory"
      ansible.builtin.file:
        path: "{{  tomcat_app_location  }}"
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: "copy .war file"
      ansible.builtin.copy:
        src: resources/todo.war
        dest: "{{  tomcat_folder_location }}/webapps/{{  tomcat_app_name  }}"
        owner: tomcat
        group: tomcat
        mode: '0644'
    
    - name: "template app.properties"
      ansible.builtin.template:
        src: resources/app.properties.j2
        dest: "{{  tomcat_app_location  }}/app.properties" 
# tasks file for tomcat
