---
- name: "Update OS"
  hosts: all
  become: yes
  tasks:
    - name: Update packages for Rocky
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "Rocky"
    - name: Update packages for Debian
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"